Feat/mana autopeering
iotaledger/goshimmer pull request #1045
Opened 2021-03-08 13:50 UTC by capossele

2021-03-29 13:26 UTC, jkrvivian commented on plugins/autopeering/parameters.go
> +	flag.Bool(CfgMana, true, "Enable/disable mana in the autopeering")
@capossele would you like to also refactor parameters as messagelayer?
or just put it to the TODO list for now :stuck_out_tongue:

2021-03-29 15:24 UTC, apenzk requested changes

2021-03-29 15:24 UTC, apenzk commented on plugins/mana/plugin.go
> +			Weight: int(manaValue * ManaScaleFactor), // scale float mana to int
- Remove manascalefactor
- use uint64

2021-03-29 15:24 UTC, apenzk commented on plugins/autopeering/autopeering.go
> +	return uint64(m * mana.ManaScaleFactor)
remove manascalefacotr

2021-03-30 14:26 UTC, jkrvivian approved these changes

2021-03-30 14:57 UTC, merged