Feat/fpc mana
iotaledger/goshimmer pull request #1085
Opened 2021-03-17 18:23 UTC by piotrm50

# Description of change

Integration of mana with FPC

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Unit tests, manual testing

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-23 13:58 UTC, apenzk requested changes

2021-03-23 13:58 UTC, apenzk commented on packages/vote/fpc/fpc.go
> +	// check almost equal
```suggestion
	// check if total mana is almost zero
```

2021-03-23 13:58 UTC, apenzk commented on plugins/messagelayer/consensus_plugin.go
> +	consensusManaNodes, _, err := GetManaMap(mana.ConsensusMana)
log the error?

2021-03-31 10:28 UTC, capossele approved these changes

2021-03-31 15:17 UTC, merged