Feat/update grafana pie charts
iotaledger/goshimmer pull request #1305
Opened 2021-05-17 17:41 UTC by piotrm50

# Description of change

Update pie chart to built-in one, instead of using external plugin in monitoring tools as well as docker network to avoid problems related to loading the plugin.
Updated docker-compose.yml in project's root.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] My code follows the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-19 16:04 UTC, capossele approved these changes

2021-05-20 06:54 UTC, lzpap requested changes

2021-05-20 06:54 UTC, lzpap commented on tools/monitoring/prometheus/prometheus.yml
> +        - goshimmer:9311
This prometheus config file is not exclusively for docker. If I wanted to run prometheus + grafana as standalone apps or system services, I can't rely on docker host name resolution.

When ran with docker, the goshimmer container should expose 9311 to the host network (127.0.0.1/0.0.0.0), and prometheus should listen to this.

2021-05-25 14:22 UTC, lzpap approved these changes

2021-05-25 14:23 UTC, merged