[docs] create and send txs
iotaledger/goshimmer pull request #1361
Opened 2021-05-26 22:24 UTC by acha-bill

2021-05-27 20:48 UTC, capossele requested changes

2021-05-27 20:48 UTC, capossele commented on docs/tutorials/send_transaction.md
> +A transaction is build from two main parts: a transaction essence, and an unlock block. The transaction essence contains all crucial information on how many and where the funds should be sent. The un
```suggestion
A transaction is built from two parts: a transaction essence, and the unlock blocks. The transaction essence contains, among other information, the amount, the origin and where the funds should be sent. The unlock block makes sure that only the owner of the funds being transferred is allowed to successfully perform this transaction.
```

2021-05-27 20:48 UTC, capossele commented on docs/tutorials/send_transaction.md
> +In order to send funds we need to have private key that can unlock our funds. If you want to use an existing seed from one of your wallets, just use the backup seed showed during a wallet creation. W
```suggestion
In order to send funds we need to have a private key that can be used to prove that we own the funds and consequently unlock them. If you want to use an existing seed from one of your wallets, just use the backup seed showed during a wallet creation. With this, we can decode the string with the `base58` library and create the `seed.Seed` instance. That will allow us to retrieve the wallet addresses (`mySeed.Address()`) and the corresponding private and public keys (`mySeed.KeyPair()`).
```

2021-05-27 20:48 UTC, capossele commented on docs/tutorials/send_transaction.md
> +After preparing the transaction essence there is a time to sign it and put the signature to the unlock block part of the transaction.
```suggestion
After preparing the transaction essence, we should sign it and put the signature to the unlock block part of the transaction.
```

2021-05-28 08:09 UTC, jkrvivian requested changes

2021-05-28 08:09 UTC, jkrvivian commented on docs/tutorials/send_transaction.md
> +PostTransaction() and IssuePayload(). The second one is more general method that sends the attached payload. We are going to use the first one that will additionally checks the transaction validity b
```suggestion
`PostTransaction()` and `IssuePayload()`. The second one is a more general method that sends the attached payload. We are going to use the first one that will additionally check the transaction validity before issuing and wait with sending the response until the message is booked.
```

2021-05-28 08:09 UTC, jkrvivian commented on docs/tutorials/send_transaction.md
> +	}
Adjust indent.

2021-05-28 12:25 UTC, jkrvivian approved these changes

2021-05-31 12:35 UTC, capossele approved these changes

2021-05-31 12:36 UTC, merged