[ratesetter] plug in ratesetter in dataflow
iotaledger/goshimmer pull request #1557
Opened 2021-07-14 09:36 UTC by acha-bill

# Description

Plugin in rate setter in data flow.

```
messageFactory-> rate setter -> messagelayer.ProcessGossipMessage
```
To apply rate setting
```
parser.MessageParsed -> rateSetter.ratesetting
```

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

2021-08-11 07:53 UTC, jkrvivian requested changes

2021-08-11 07:53 UTC, jkrvivian commented on packages/spammer/spammer.go
> +		estimatedDuration := messagelayer.Tangle().RateSetter.Estimate()
We should avoid importing plugins in packages,
maybe make this estimation function a parameter of `run()`?

2021-08-11 08:23 UTC, jkrvivian commented
What do you think if we also use the `Estimate()` in `/data` API?
First, get the estimation of waiting time, if the node needs to wait over a threshold time window,
then we return an error message, suggesting users change a node.

2021-08-12 08:57 UTC, jkrvivian approved these changes

2021-08-23 11:58 UTC, Wollac approved these changes

2021-11-12 08:29 UTC, karimodm commented
PR is ready to merge, but let's put this on hold as it will significantly change UX, not a priority atm!

2022-06-20 16:18 UTC, jonastheis requested changes

2022-06-20 16:18 UTC, jonastheis commented on client/wallet/webconnector.go
> +
Couldn't the client expose such a functionality? And you just call it from here?

2022-06-20 16:18 UTC, jonastheis commented on client/wallet/webconnector.go
> +	time.Sleep(rateSetterInfo.Estimate)
Couldn't the client expose such a functionality? And you just call it from here?

2022-06-21 06:17 UTC, piotrm50 commented on client/evilspammer/spamming_functions.go
> +	//time.Sleep(time.Duration(rand.Float64()*100) * time.Millisecond)
Uncommented it. It should always be executed because we don't want a 100 goroutines to query the rate setter at almost the same time.

2022-06-21 06:21 UTC, piotrm50 commented on client/evilwallet/evilwallet.go
> +	}
No, but it's just utility functions and `SendCustomConflicts` which apparently is not used anywhere so I didn't add it there.

2022-06-21 06:31 UTC, piotrm50 commented on tools/integration-tests/tester/framework/parameters.go
> +	c.RateSetter.RateSetterParametersDefinition.Enable = false
It took me a while :D 
`c.RateSetter.Enabled = true` - this line allows the framework to include the rate setter parameters in the arguments it passes when running goshimmer.

`c.RateSetter.RateSetterParametersDefinition.Enable` - this line is the parameter itself that disables the rate setter.

2022-06-21 07:07 UTC, piotrm50 commented on packages/tangle/ratesetter.go
> +)
Changed it

2022-06-21 07:22 UTC, jonastheis approved these changes

2022-06-21 10:21 UTC, merged