Docs/migrate to docusarus
iotaledger/goshimmer pull request #1558
Opened 2021-07-14 10:35 UTC by lucas-tortora

# Description of change

### Migrated to Docusaurus:

* Delete mdbooks
* Copied docs folder to docOps
* Initiated docusaurus
* Closed JSX tags that were causing compilation errors
* Moved images to docsOps/static
* Fixed broken links
* Improved slugs

**NO CONTENT/TEXT WAS EDITED, ONLY HOW WE SERVE IT**

## Links to any relevant issues

[Edit all text with our style guide](https://github.com/iotaledger/docs.iota.org/issues/2)

## Type of change
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix

## How the change has been tested

You can follow the docs/README.md file for running docusaurus.
The documentation was served and reviewed locally.  

## Change checklist
- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation

2021-07-14 10:56 UTC, huhn511 requested changes
- [ ] remove doubled gh-action workflow
- [ ] change landing page content

2021-07-14 10:56 UTC, huhn511 commented on .github/deploy_docs_to_gh-pages.yml
> +    branches: [migrateToDocusaurus, dev, main]
change `dev` to ´develop´

2021-07-14 10:56 UTC, huhn511 commented on .github/deploy_docs_to_gh-pages.yml
> +          publish_dir: ./docOps/build
add `cname: goshimmer.docs.iota.org`

2021-07-14 10:56 UTC, huhn511 commented on docOps/docusaurus.config.js
> +  title: 'Goshimmer',
Change to `goShimmer`

2021-07-14 19:41 UTC, anistark commented
I can see these variations of the name:
1. GoShimmer
2. goShimmer
3. Goshimmer
4. goshimmer

I think we should stick to 1 particular naming convention everywhere. I believe the official one is "GoShimmer". Or if we don't have an official one, let's settle for one.

2021-07-15 09:05 UTC, capossele approved these changes
Super awesome!

2021-07-15 09:16 UTC, huhn511 approved these changes
LGTM! 👍

2021-07-15 09:17 UTC, merged