Docs - Changed docOps directory name to documentation
iotaledger/goshimmer pull request #1567
Opened 2021-07-20 06:39 UTC by lucas-tortora

# Description of change

* Changed docOps directory name to documentation
* Updated deploy-docs-to-gh-pages.yml workflow accordingly

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Fix

## How the change has been tested

Changes where tested locally.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation

2021-07-26 13:19 UTC, apenzk commented on documentation/README.md
>  This command generates static content into the `build` directory and can be served using any static contents hosting service.
```suggestion
This command generates static content into the `build` directory and can be served using any static contents hosting service. E.g. in the browser attempt to load via http://localhost:3000/.
```

2021-07-27 19:42 UTC, apenzk approved these changes
Looks good

2021-07-27 19:45 UTC, apenzk requested changes
There should be an instruction in which file the sidebar in the docs is changed and organised. And how to do it

2021-07-28 08:17 UTC, lucas-tortora commented
> Should there be an instruction about how to change the sidebar in the docs and how to reference files. I.e. discuss how the sidebars.js works. But where could this be put?

I've added new sections addressing these topics in the `documentation/README.md` file.

2021-07-29 13:48 UTC, closed without merging