Improve spammer precision
iotaledger/goshimmer pull request #1600
Opened 2021-08-04 06:26 UTC by daria305

# Description of change
Fixes #1592 

 - Change the spammer tool to use Ticker instead of waiting to control the rate
 - Change rate unit from mpm to mps:
`curl --location 'http://localhost:8080/spammer?cmd=start&mps=100&imif=poisson'`

 - Add missing imif flag to web API ToggleSpammer() client API

## Type of change
- Enhancement (a non-breaking change which adds functionality)
- Documentation Update

## How the change has been tested
HTTP, web API, spammer go script tested on local docker net

2021-08-04 11:55 UTC, capossele requested changes
Looks good overall. One comment though related to the rate now expressed in seconds. This limits the rate of the spammer as it cannot issue slower than 1 MPS and, depending on the aMana, that could be too much. Should we maybe find a solution to be more flexible regarding the setting of the rate?

2021-08-04 14:25 UTC, daria305 commented
> Looks good overall. One comment though related to the rate now expressed in seconds. This limits the rate of the spammer as it cannot issue slower than 1 MPS and, depending on the aMana, that could be too much. Should we maybe find a solution to be more flexible regarding the setting of the rate?

I've added an optional parameter `unit` that by default is mps but can be changed to mpm.

2021-08-05 02:40 UTC, jkrvivian approved these changes

2021-08-09 17:27 UTC, capossele approved these changes

2021-08-12 08:04 UTC, merged