Dev/consensus finality properties
iotaledger/goshimmer pull request #1628
Opened 2021-08-13 12:57 UTC by karimodm

# Description of change

Remove all references to Liked / Finalized / InclusionState and the like.

2021-08-13 15:17 UTC, jonastheis requested changes

2021-08-13 15:17 UTC, jonastheis commented on packages/consensus/finality/finality_gadget.go
>  	IsMarkerConfirmed(marker *markers.Marker) (confirmed bool)
Should be removed as it is now part of `tangle.ConfirmationOracle`.
```suggestion
```

2021-08-13 15:17 UTC, jonastheis commented on plugins/dashboard/explorer_routes.go
> +	PendingMana float64                    `json:"pendingMana"`
Shouldn't we somehow tell the explorer what is considered to be "confirmed"?

2021-08-18 09:32 UTC, jonastheis approved these changes

2021-08-19 06:36 UTC, luca-moser approved these changes

2021-08-19 07:21 UTC, merged