Add grade of finality time and remove eligible flag
iotaledger/goshimmer pull request #1636
Opened 2021-08-18 10:37 UTC by jonastheis

This PR adds the time the grade of finality was set to the message metadata, transaction metadata and output metadata. It adds it to the corresponding APIs and diagnostic APIs.

2021-08-18 13:23 UTC, karimodm requested changes
A couple of references left:

* tangle.go: `New` method, `Events` `MessageEligible`
* tipmanager.go: `AddTip`'s comment
* consensusmanager.go: `MessageEligible` method

2021-08-18 14:23 UTC, jonastheis commented
> consensusmanager.go: MessageEligible method
This will be removed with https://github.com/iotaledger/goshimmer/pull/1638

2021-08-19 06:42 UTC, luca-moser approved these changes

2021-08-19 10:12 UTC, karimodm approved these changes

2021-08-19 10:15 UTC, merged