Inherit markers from strong and like parents
iotaledger/goshimmer pull request #1640
Opened 2021-08-19 10:17 UTC by jonastheis

# Description of change
This PR changes the inheritance of markers to not only consider the strong parents but also the like parents.

In the example below, `message 1` is considered to be in the past cone of `message 6` even though they are not connected via strong parents but like parent. Consequently, AW will be propagated from `message 6` to `message 1`.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/4181434/130051027-18ff9fb7-db0d-4606-88dc-f822cd7f7eba.png">

2021-08-19 11:31 UTC, karimodm requested changes

2021-08-19 11:31 UTC, karimodm commented on packages/tangle/booker.go
> +// structureDetailsOfStrongAndLikeParents is an internal utility function that returns a list of StructureDetails of all the
Add liked parents to comment.

2021-08-19 11:31 UTC, karimodm commented on packages/tangle/images/TestBookerMarkerMappings.html
> +<body><div class="mxgraph" style="max-width:100%;border:1px solid transparent;" data-mxgraph="{&quot;highlight&quot;:&quot;#0000ff&quot;,&quot;lightbox&quot;:false,&quot;nav&quot;:true,&quot;resize&q
We still have an obsolete MD version of this. Let's delete it if we decided not to update it :sunglasses:

2021-08-23 08:43 UTC, luca-moser approved these changes

2021-08-23 08:59 UTC, merged