Fix: fixed broken GradeOfFinality function
iotaledger/goshimmer pull request #1671
Opened 2021-08-31 21:21 UTC by hmoog

# Description of change

This PR fixes a bug in the GradeOfFinality function that currently always returns the GradeOfFinality of the Branch instead of the Transaction.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-01 14:26 UTC, jonastheis requested changes
Also remove the `GradeOfFinality` property from the web api json models as well as the diagnostic API and its integration test.

2021-09-01 15:11 UTC, hmoog commented on packages/ledgerstate/utxo_dag.go
> +	normalizedBranches, err := u.branchDAG.normalizeBranches(NewBranchIDs(branchID))
Because then we might still have unnecessary candidates that are being processed unnecessarily.

2021-09-01 15:12 UTC, hmoog commented on packages/ledgerstate/utxo_dag.go
> +		return gof.High, nil
I am not sure I understand - did we make the MasterBranch configurable?

2021-09-01 15:12 UTC, hmoog commented on packages/ledgerstate/utxo_dag.go
> -
I don't get it - The PR deletes it?

2021-09-02 09:47 UTC, jonastheis approved these changes

2021-09-02 10:39 UTC, merged