Remove aggregated branches
iotaledger/goshimmer pull request #2070
Opened 2022-02-22 20:07 UTC by jonastheis

# Description of change

To simplify the concepts of the BranchDAG, we remove the AggregatedBranches from the code base and just carry `BranchIDs` in every object (lots of duplicate branches might be stored but due to merge to master it should be limited and go back to master branch quickly). Later on we can introduce a storage optimization aka `CompressedBranchIDs` to handle deduplication on the storage layer itself. In that way the interface of `Transaction` and `Output` does not change regardless of how the branch IDs are actually stored. 

## Type of change
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-02-28 15:27 UTC, karimodm requested changes
Great work man, thanks!

2022-02-28 15:27 UTC, karimodm commented on packages/tangle/approvalweightmanager.go
> +	a.tangle.Storage.BranchWeight(branchID).Consume(func(branchWeight *BranchWeight) {
I wrote this so I shouldn't review it.

2022-02-28 15:27 UTC, karimodm commented on packages/tangle/ledgerstate.go
> +	return l.BranchIDs(transactionID).Contains(ledgerstate.NewBranchID(transactionID))
```
// IsConflicting returns true if the Transaction is conflicting with another Transaction (has its own Branch).
func (t *TransactionMetadata) IsConflicting() bool {
	branchIDs := t.BranchIDs()
	return len(branchIDs) == 1 && branchIDs.Contains(NewBranchID(t.ID()))
}
```

should we do the same `len(branchIDs) == 1` here?

2022-03-02 12:47 UTC, karimodm approved these changes

2022-03-02 18:11 UTC, hmoog requested changes
I have left some comments

2022-03-02 18:11 UTC, hmoog commented on packages/tangle/message.go
> +	m.addedBranchIDs = addedBranchIDs.Clone()
again - check for equality and return modified false.

2022-03-02 18:11 UTC, hmoog commented on packages/tangle/message.go
> +	m.subtractedBranchIDs = subtractedBranchIDs.Clone()
check for equality and return false

2022-03-02 18:11 UTC, hmoog commented on packages/txstream/tangleledger/tangleledger.go
> +	if found {
shouldnt it only execute the callback if ALL branches have high gof AND the tx has high gof?

2022-03-04 13:25 UTC, merged