Add notarization manager unit tests
iotaledger/goshimmer pull request #2311
Opened 2022-06-27 07:24 UTC by jkrvivian

# Description of change

Close #2245 #2283 #2284 

## Type of change

- Enhancement

## Change checklist

- [ ] My code follows the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-27 13:08 UTC, daria305 requested changes
Tests seems to cover nicely the flow and epoch changes :+1:  
I see we do not check committments itself, but it's fine as it is something we could do later with proofs. 
I don't like time.Sleep, not sure how hard it would be to ged rid of it

2022-06-27 13:08 UTC, daria305 commented on packages/notarization/manager_test.go
> +	// Message3, issuing time epoch 3
We could start from here also checking if the reference to the `prevEC` is correct

2022-06-27 14:06 UTC, karimodm commented on packages/notarization/manager_test.go
>  		sfg.HandleMarker(e.Marker, e.Weight)
The doggo really doesn't complain about these discarded return values; I also find it pretty ugly! Do we need it?

2022-06-27 14:08 UTC, karimodm commented on packages/epoch/types.go
>  // CurrentEI returns the EI at the current synced time.
True, but it seems like a useful function to keep around!

2022-06-27 14:09 UTC, karimodm commented on packages/notarization/manager_test.go
> +	assert.Equal(t, uint64(3), m.pendingConflictsCounters[3])
You are right; also the NotNil is not needed as the assignation woul panic if nil

2022-06-27 14:22 UTC, karimodm commented on packages/notarization/manager_test.go
> +	m.epochCommitmentFactory.storage.SetLastCommittedEpochIndex(0)
done

2022-06-28 07:22 UTC, jkrvivian commented on packages/notarization/manager_test.go
>  		sfg.HandleMarker(e.Marker, e.Weight)
I'll go for what it is now :grimacing:

2022-06-28 07:36 UTC, daria305 commented on packages/notarization/manager_test.go
>  		sfg.HandleMarker(e.Marker, e.Weight)
For me it looks normal, as it indicates that you not handle error on purpose, and not just forgot about this. And my goland always underline unhandled errors

2022-06-30 08:53 UTC, daria305 approved these changes

2022-06-30 08:54 UTC, merged