Implement simplified faucet
iotaledger/goshimmer pull request #2391
Opened 2022-08-19 13:43 UTC by jkrvivian

# Description of change

## Type of change

- Breaking change

## Change checklist

- [ ] My code follows the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-19 14:37 UTC, piotrm50 requested changes
We should use `client/wallet` package to manage funds and addresses instead of having to manage it in the faucet plugin. It'd make the code more simple and readable. 
If we configure the wallet to reuse the same address, then it will always read the correct state from the tangle. 
It also would be nice to only handle requests that are not older than X minutes, because otherwise in case of faucet node restart, it would try to fullfill all the requests again.

2022-08-19 14:37 UTC, piotrm50 commented on plugins/faucet/plugin.go
> +		go _faucet.Start(ctx, requestChan)
Is a new goroutine necessary here? In the next line we block on the ctx channel, and the goroutine waits for the same channel. Maybe it's not necessary to wait for the context here but simlpy make the `_faucet.Start` blocking?

2022-08-19 14:37 UTC, piotrm50 commented on plugins/faucet/plugin.go
> +		_faucet.DeriveStateFromTangle()
If we use `client/wallet` package then it automatically does that upon creation.

2022-08-19 14:37 UTC, piotrm50 commented on plugins/faucet/faucet.go
> +func (f *Faucet) DeriveStateFromTangle() {
This shouldn't be necessary if we use `client/wallet`, because it initializes the state automatically.

2022-08-22 15:25 UTC, piotrm50 requested changes

2022-08-22 15:25 UTC, piotrm50 commented on plugins/faucet/faucet.go
> +	seed, lastAddressIndex, spentAddresses, assetRegistry, err := importWalletStateFile(walletStates)
You don't need to dump the wallet file. Wallet should always be initialized from seed.

2022-08-22 15:25 UTC, piotrm50 commented on plugins/faucet/parameters.go
> +	FaucetWalletFile string `default:"faucet.wallet" usage:"the states that is preserved for faucet wallet"`
We don't need to dump the wallet to a file as we always pass the seed.

2022-08-22 15:25 UTC, piotrm50 commented on plugins/faucet/plugin.go
>  	blacklist         *orderedmap.OrderedMap[string, bool]
Remove the whole blacklist logic along with those fields as we don't need it and want to simplify as much as possilbe

2022-08-25 06:35 UTC, piotrm50 requested changes
Remove the faucet request window check, fix the tests and I think it's good to go :)

2022-08-25 06:35 UTC, piotrm50 commented on plugins/faucet/plugin.go
> +	faucetRequestWindow = 3 * time.Minute
After all we might not need this because the faucet does not pledge tokens when it's not bootstrapped, which ultimately covers this check.

2022-08-25 15:28 UTC, jonastheis requested changes
It looks already pretty good and makes everything so much simpler. But I think some things can still be improved

2022-08-25 15:28 UTC, jonastheis commented on plugins/faucet/plugin.go
>  		}
Can't comment on the actual line: do we really still need `waitForMana`? After the node is bootstrapped, can't we simply check if it has mana and if not we log an error and return?

2022-08-25 15:28 UTC, jonastheis commented on plugins/faucet/connector.go
> +func (f *FaucetConnector) GetAllowedPledgeIDs() (pledgeIDMap map[mana.Type][]string, err error) {
Not sure how this is internally used but it seems that there shouldn't be any allowed pledge IDs be configured on the faucet node and then the mana plugin will always just return the faucet nodeID in the allowed list. The pledges are still created correctly. So maybe this function can be simplified by just returning the current nodeID ?

2022-08-26 10:59 UTC, jonastheis approved these changes

2022-08-26 13:44 UTC, piotrm50 approved these changes

2022-08-29 11:28 UTC, merged