Load genesis timestamp and slot duration from snapshot
iotaledger/goshimmer pull request #2598
Opened 2023-03-02 17:59 UTC by alexsporn

2023-03-03 16:12 UTC, hmoog requested changes
LGTM

2023-03-03 16:12 UTC, hmoog commented on packages/protocol/engine/notarization/manager.go
> +	if _, err = m.Attestations.Delete(NewAttestation(block, m.storage.Settings.SlotTimeProvider())); err != nil {
Shouldn't the Attestations also use a SlotTimeProvider func?

2023-03-03 16:24 UTC, alexsporn commented on packages/protocol/engine/notarization/manager.go
> +	if _, err = m.Attestations.Delete(NewAttestation(block, m.storage.Settings.SlotTimeProvider())); err != nil {
They just use it in the initializer once

2023-03-06 10:03 UTC, hmoog approved these changes

2023-03-06 10:04 UTC, merged