Modularize Ledger
iotaledger/goshimmer pull request #2602
Opened 2023-03-06 16:36 UTC by alexsporn

Note: this does not yet looks at minimizing or changing the Ledger API. It is pure code restructuring to avoid cyclic dependencies. All currently used ledger API are exposed in the interface as is.

2023-03-07 11:17 UTC, hmoog requested changes
Only minor comments

2023-03-07 11:17 UTC, hmoog commented on packages/protocol/engine/tsc/manager.go
> +	o.Lock()
RLock?

2023-03-07 11:17 UTC, hmoog commented on plugins/protocol/plugin.go
> +	ledgermodule "github.com/iotaledger/goshimmer/packages/protocol/ledger/realitiesledger"
remove alias

2023-03-08 08:27 UTC, alexsporn commented on packages/protocol/engine/tsc/manager.go
> +	o.Lock()
This is a normal `sync.Mutex`. I just added the `Size()` for the tests, because they where previously calling `Len()` on the private field

2023-03-08 12:28 UTC, hmoog approved these changes

2023-03-09 16:59 UTC, hmoog approved these changes
I had some minor remarks (missing comments and so on) but we can also address them in a later PR.

2023-03-09 16:59 UTC, hmoog commented on packages/protocol/engine/consensus/blockgadget/testframework.go
> +	Ledger        *mempool.TestFramework
rename to MemPool

2023-03-09 16:59 UTC, hmoog commented on packages/protocol/engine/consensus/blockgadget/testframework.go
> +func NewDefaultTestFramework(t *testing.T, workers *workerpool.Group, ledger mempool.MemPool, optsGadget ...options.Option[Gadget]) *TestFramework {
rename ledger to memPool

2023-03-09 16:59 UTC, hmoog commented on packages/protocol/engine/engine.go
> +	e.Events.MemPool.TransactionAccepted.Hook(func(event *mempool.TransactionEvent) {
Move MemPool events into the ledger events `e.Events.Ledger.MemPool`

2023-03-09 16:59 UTC, hmoog commented on packages/protocol/engine/events.go
> +	MemPool             *mempool.Events
Expose Ledger events here with MemPool as subevents

2023-03-09 16:59 UTC, hmoog commented on packages/protocol/engine/ledger/ledger.go
> +	MemPool() mempool.MemPool
Add comment for the getter

2023-03-10 08:06 UTC, merged