Starting node from disk
iotaledger/goshimmer pull request #2620
Opened 2023-04-01 09:11 UTC by karimodm

# Description of change

Node starts from disk!

2023-04-04 12:47 UTC, jonastheis approved these changes

2023-04-05 07:05 UTC, piotrm50 requested changes

2023-04-05 07:05 UTC, piotrm50 commented on packages/protocol/engine/notarization/slotnotarization/manager.go
> +			acceptedTimeFunc:          e.Clock.Accepted().Time,
I think this should be put into `e.HookConstructed` or `e.HookConstructed` callback, in case Notarization Manager is initialized before the clock, and clock is not available yet.

2023-04-05 10:02 UTC, piotrm50 approved these changes

2023-04-05 10:27 UTC, merged