Simplify debugging through synchronous data flow
iotaledger/goshimmer pull request #2622
Opened 2023-04-01 18:58 UTC by hmoog

# Description of change

To speed up the debugging process, we temporarily make the processing of blocks synchronous.

After stabilizing the code base and removing the last bugs, we can re-introduce multi-threading on a component by component basis without having to look for race conditions in all components simultaneously.

In addition to the named changes, this PR already fixes a few deadlocks in the data flow.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-04-11 06:59 UTC, piotrm50 requested changes

2023-04-11 06:59 UTC, piotrm50 commented on packages/network/p2p/manager.go
> +	m.stopMutex.Unlock()
stop mutex is not unlocked in the `if` above

2023-04-11 06:59 UTC, piotrm50 commented on packages/protocol/engine/ledger/mempool/realitiesledger/booker.go
> +	//
```suggestion
```

2023-04-11 06:59 UTC, piotrm50 commented on packages/protocol/engine/tangle/blockdag/inmemoryblockdag/blockdag.go
> +		//defer b.solidifierMutex.Unlock()
```suggestion
		//b.solidifierMutex.RLock()
		//defer b.solidifierMutex.RUnlock()
```

2023-04-11 06:59 UTC, piotrm50 commented on packages/protocol/engine/tangle/blockdag/inmemoryblockdag/blockdag.go
> +	//defer b.solidifierMutex.Unlock()
```suggestion
	//b.solidifierMutex.RLock()
	//defer b.solidifierMutex.RUnlock()
```

2023-04-11 06:59 UTC, piotrm50 commented on packages/protocol/engine/tangle/blockdag/testframework.go
> +		fmt.Println("issue", alias)
```suggestion

```

2023-04-11 06:59 UTC, piotrm50 commented on packages/protocol/engine/tangle/booker/markerbooker/booker.go
> +	//defer b.sequenceEvictionMutex.Unlock()
```suggestion
	//b.sequenceEvictionMutex.RLock()
	//defer b.sequenceEvictionMutex.RUnlock()
```

2023-04-11 06:59 UTC, piotrm50 commented on packages/protocol/engine/tangle/booker/markerbooker/booker.go
> +	//defer b.sequenceEvictionMutex.Unlock()
```suggestion
	//b.sequenceEvictionMutex.RLock()
	//defer b.sequenceEvictionMutex.RUnlock()
```

2023-04-11 06:59 UTC, piotrm50 commented on packages/protocol/engine/tangle/booker/markerbooker/booker.go
> +	defer b.evictionMutex.Unlock()
This used to be a RLock

```suggestion
	b.evictionMutex.RLock()
	defer b.evictionMutex.RUnlock()
```

2023-04-11 06:59 UTC, piotrm50 commented on packages/protocol/engine/tangle/booker/markerbooker/booker.go
> +	defer b.sequenceEvictionMutex.Unlock()
```suggestion
	b.sequenceEvictionMutex.RLock()
	defer b.sequenceEvictionMutex.RUnlock()
```

2023-04-17 11:09 UTC, hmoog commented on packages/network/p2p/manager.go
>  		return ErrNotRunning
Unlock is missing

2023-04-19 11:01 UTC, piotrm50 approved these changes

2023-04-20 06:53 UTC, merged