dRNG refactor
iotaledger/goshimmer pull request #727
Opened 2020-09-09 09:45 UTC by capossele

2020-09-10 09:28 UTC, jkrvivian commented on packages/drng/collective_beacon_payload.go
> +func (payload *CollectiveBeaconPayload) Bytes() (bytes []byte) {
Rename the method receiver to a single character. Like this:
```suggestion
func (p *CollectiveBeaconPayload) Bytes() (bytes []byte) {
```

2020-09-10 09:28 UTC, jkrvivian commented on packages/drng/common.go
> +package drng
Maybe rename the file to `constant.go`?

2020-09-10 09:28 UTC, jkrvivian commented on packages/drng/dispatcher.go
> +func (drng *DRNG) Dispatch(issuer ed25519.PublicKey, timestamp time.Time, payload *Payload) error {
Single character for method receiver here.
```suggestion
func (d *DRNG) Dispatch(issuer ed25519.PublicKey, timestamp time.Time, payload *Payload) error {
```

2020-09-10 09:28 UTC, jkrvivian commented on packages/drng/events.go
> +	// Collective signature of the previous beacon.s
Typo.
```suggestion
	// Collective signature of the previous beacons.
```

2020-09-21 11:14 UTC, jonastheis requested changes

2020-09-21 11:14 UTC, jonastheis commented on packages/drng/payload.go
>  func (payload *Payload) Type() tangle.PayloadType {
```suggestion
func (p *Payload) Type() tangle.PayloadType {
```

2020-09-23 08:51 UTC, jonastheis approved these changes

2020-09-23 08:53 UTC, merged