refactor: Flatten messagelayer
iotaledger/goshimmer pull request #732
Opened 2020-09-10 08:02 UTC by jkrvivian

# Description of change

This PR copies files from the `binary/messagelayer` to `tangle/` with a flat structure and **does not** resolve the import issues from other packages or plugins, which would be done in the next PR.

This PR also includes: error messages annotation and using single character for receiver method.

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2020-09-11 14:47 UTC, jonastheis requested changes

2020-09-11 14:47 UTC, jonastheis commented on packages/tangle/data_payload.go
> +	ObjectName = "data"
I think for now it's fine to name it `Object` but eventually we need to decide to stick to either `Object` or `Payload` and change it across the whole codebase. Even the file is called `data_payload.go`.

2020-09-11 14:47 UTC, jonastheis commented on packages/tangle/approver.go
> +func (cachedApprover *CachedApprover) Unwrap() *Approver {
```suggestion
func (c *CachedApprover) Unwrap() *Approver {
```
or `a` would also be fine

2020-09-14 03:23 UTC, jkrvivian commented on packages/tangle/message.go
> +func ParseMessageID(marshalUtil *marshalutil.MarshalUtil) (MessageID, error) {
okay, then I'll use the entity name as the prefix. :smile:

2020-09-14 06:41 UTC, jkrvivian commented on packages/tangle/requester.go
> +	requester := &Requester{
The single character is used for method receiver, yet `requester ` is a local variable, it's ok to stay like this I suppose.

2020-09-14 18:04 UTC, jonastheis approved these changes

2020-09-14 21:20 UTC, hmoog commented on packages/tangle/requester.go
> +	requester := &Requester{
agree

2020-09-16 09:00 UTC, capossele approved these changes
Nice work!

2020-09-16 09:02 UTC, hmoog requested changes
I think those would be the last changes - rest LGTM

2020-09-16 11:33 UTC, hmoog approved these changes

2020-09-16 11:37 UTC, merged