refactor: Remove binary/messagelayer and replace with tangle package
iotaledger/goshimmer pull request #740
Opened 2020-09-15 08:23 UTC by jkrvivian

# Description of change

*  use tangle package instead
* remove binary/messagelayer

## Type of change
- Breaking change

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

2020-09-15 10:03 UTC, jonastheis requested changes

2020-09-15 10:05 UTC, jonastheis reviewed
I think it would have been easier to review if the merge target would be the `refactor/messagelayer_pkg` branch. Then the changes related to flattening would not be in here. Next time you could consider this. 

But overall great work!

2020-09-16 05:48 UTC, jkrvivian commented
> I think it would have been easier to review if the merge target would be the `refactor/messagelayer_pkg` branch. Then the changes related to flattening would not be in here. Next time you could consider this.
> 
> But overall great work!

Thanks, @jonastheis !
I actually plan to ask for reviews until the flatten PR is merged, that way only the importing commits are left which makes this PR cleaner.  I should've opened this as draft. :sweat_smile:

2020-09-16 14:48 UTC, jonastheis approved these changes

2020-09-17 10:46 UTC, hmoog reviewed
LGTM

2020-09-21 05:45 UTC, merged